name: Publish 'latest' image

on:
  release:
    types:
      - "created"

jobs:
  cd:
    uses: decentraland/actions/.github/workflows/build-quay-main.yml@main
    with:
      service-name: explorer-bff
      deployment-environment: dev
      docker-tag: latest ${{ github.event.release.tag_name }}
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
