name: CI/CD on main branch

on:
  push:
    branches:
      - "main"

jobs:
  cd:
    uses: decentraland/actions/.github/workflows/build-quay-main.yml@main
    with:
      service-name: explorer-bff
      deployment-environment: dev
      docker-tag: next
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
