name: CI/CD on main branch

on:
  push:
    branches:
      - "main"

jobs:
  cd:
    uses: decentraland/platform-actions/.github/workflows/apps-docker-next.yml@main
    with:
      service-name: explorer-bff
    secrets: inherit
